name: uptime-kuma

services:
  uptime-kuma:
    image: louislam/uptime-kuma:2.0.0-beta.4
    container_name: uptime-kuma
    ports:
      - "3001:3001"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - uptime-kuma-network
    environment:
      - UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN=0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  caddy:
    image: caddy:2.10.2-alpine
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
    environment:
      DOMAIN: ${DOMAIN:?DOMAIN is required}
    networks:
      - uptime-kuma-network
    depends_on:
      uptime-kuma:
        condition: service_healthy

volumes:
  caddy_data:
  caddy_config:

networks:
  uptime-kuma-network:
    driver: bridge
