services:
  uptime-kuma:
    image: louislam/uptime-kuma:2.0.0-beta.4
    container_name: uptime-kuma
    volumes:
      - uptime-kuma-data:/app/data
    restart: unless-stopped
    networks:
      - rigel-network
    environment:
      - UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN=0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  rigel-network:
    external: true

volumes:
  uptime-kuma-data: